<#
.SYNOPSIS
Prepares the link of the Windows image with the static C runtime (/MT): crt_shim.obj, the CRT import pointers.

.DESCRIPTION
native-image links the image with the dynamic C runtime (/MD): the static libraries of the JDK in GraalVM
(lib\static\windows-amd64) are compiled with /MD and call the CRT through the __imp_<name> pointers of its import
libraries. To link the image with the static CRT (no VCRUNTIME140.dll, no api-ms-win-crt-*.dll), this script:

  1. lists the CRT functions that these libraries call through __imp_ pointers: the undefined __imp_ symbols of the
     libraries that the import libraries of the dynamic CRT (ucrt.lib, vcruntime.lib, msvcrt.lib) export, including
     the POSIX names (strdup) of the exported _strdup;
  2. assembles crt_shim.obj (ml64), which defines each __imp_<name> as a pointer to <name> of the static CRT.

The windowsStaticRuntime profile of pom.xml links the image with crt_shim.obj, the static CRT libraries (libcmt.lib,
libvcruntime.lib, libucrt.lib) and without the default dynamic ones (-H:NativeLinkerOption). The explicit libcmt.lib is
linked although native-image passes /NODEFAULTLIB:LIBCMT: that option removes only the default library.

A function missing from the object fails the link with LNK2019 (unresolved __imp_...), it does not bring the dynamic
CRT back. Requires the MSVC environment (dumpbin, ml64, LIB), as native-image does.

.PARAMETER GraalVmHome
The GraalVM that builds the image.

.PARAMETER OutputDirectory
Where crt_shim.asm, crt_shim.obj and crt-functions.txt are written.
#>
param(
    [Parameter(Mandatory = $true)][string]$GraalVmHome,
    [Parameter(Mandatory = $true)][string]$OutputDirectory
)

$ErrorActionPreference = 'Stop'

function Get-Tool([string]$Name) {
    $tool = Get-Command $Name -ErrorAction SilentlyContinue
    if (-not $tool) {
        throw "$Name is not in PATH: run in the MSVC environment (vcvars64.bat, VsDevCmd.bat -arch=amd64)"
    }
    return $tool.Source
}

function Find-Library([string]$Name) {
    foreach ($directory in $env:LIB -split ';' | Where-Object { $_ }) {
        $path = Join-Path $directory $Name
        if (Test-Path $path) {
            return $path
        }
    }
    throw "$Name is not found in LIB ($env:LIB)"
}

$dumpbin = Get-Tool 'dumpbin.exe'
$ml64 = Get-Tool 'ml64.exe'

# The functions of the dynamic CRT: the exports of its import libraries.
$crt = [System.Collections.Generic.HashSet[string]]::new()
foreach ($library in 'ucrt.lib', 'vcruntime.lib', 'msvcrt.lib') {
    foreach ($line in & $dumpbin /nologo /exports (Find-Library $library)) {
        if ($line -match '^\s+(\w+)$') {
            [void]$crt.Add($Matches[1])
        }
    }
}

# The __imp_ symbols of the static libraries of GraalVM that native-image may link into the image.
$libraries = @(Get-ChildItem (Join-Path $GraalVmHome 'lib\static\windows-amd64') -Filter *.lib) +
        @(Get-ChildItem (Join-Path $GraalVmHome 'lib\svm\clibraries\windows-amd64') -Filter *.lib)
if ($libraries.Count -eq 0) {
    throw "No static libraries in $GraalVmHome\lib"
}
$imported = [System.Collections.Generic.SortedSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($library in $libraries) {
    foreach ($line in & $dumpbin /nologo /symbols $library.FullName) {
        if ($line -match 'UNDEF\s+notype\s+External\s+\|\s+__imp_(\w+)') {
            [void]$imported.Add($Matches[1])
        }
    }
}
$functions = @($imported | Where-Object { $crt.Contains($_) -or $crt.Contains("_$_") })

New-Item -ItemType Directory -Force $OutputDirectory | Out-Null
$functions | Set-Content -Encoding ascii (Join-Path $OutputDirectory 'crt-functions.txt')

$asm = [System.Collections.Generic.List[string]]::new()
$asm.Add('; Generated by New-CrtShim.ps1: the __imp_ pointers of the dynamic CRT for the objects compiled with /MD,')
$asm.Add('; pointing at the functions of the static CRT.')
foreach ($function in $functions) {
    $asm.Add("EXTRN ${function}:PROC")
}
$asm.Add('.data')
$asm.Add('ALIGN 8')
foreach ($function in $functions) {
    $asm.Add("PUBLIC __imp_$function")
    $asm.Add("__imp_$function DQ $function")
}
$asm.Add('END')
$asmFile = Join-Path $OutputDirectory 'crt_shim.asm'
$objFile = Join-Path $OutputDirectory 'crt_shim.obj'
$asm | Set-Content -Encoding ascii $asmFile

& $ml64 /nologo /c "/Fo$objFile" $asmFile | Out-Host
if ($LASTEXITCODE -ne 0) {
    throw "ml64 failed with exit code $LASTEXITCODE"
}

Write-Host "[INFO] $($functions.Count) CRT functions of $($libraries.Count) libraries: $OutputDirectory"
