package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildAndDeployForWindowsDebug'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildAndDeployForWindowsDebug")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
