package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildAndDeployForLinuxAarch64WindowsAndMacOS'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildAndDeployForLinuxAarch64WindowsAndMacOS")) {
    check(allowExternalStatus == false) {
        "Unexpected option value: allowExternalStatus = $allowExternalStatus"
    }
    allowExternalStatus = true
}
