package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'CopyServiceImages'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("CopyServiceImages")
    name = "Copy service images"

    params {
        password("env.jfrogPass", "credentialsJSON:d288798f-47b9-4fbb-8463-a68be694481d")
        param("env.srcRepo", "https://dxfeed.jfrog.io/ui/repos/tree/General/docker/dxfeed-api/graalvm/linux-aarch64-jdk-23.0.2")
        param("env.target.repo", "nexus-docker-graalvm.in.devexperts.com")
    }

    vcs {
        root(RelativeId("SshGitStashInDevexpertsCom7999enDxfeedGraalNativeApiGitRefsHeadsMainTags"))
    }

    steps {
        script {
            name = "test"
            id = "test"
            scriptContent = """
                echo "Installing Skopeo"
                apt-get update
                apt-get install -y skopeo
                
                image_tag=${'$'}(echo "%env.srcRepo%" | cut -d "/" -f 11)
                echo ${'$'}image_tag
                
                
                skopeo copy \
                  --src-creds amordovskii:%env.jfrogPass% \
                  --dest-creds %dxcity.login%:%dxcity.password% \
                  docker://%env.srcRepo% \ 
                  docker://%env.target.repo%/${'$'}image_tag
            """.trimIndent()
            dockerImage = "ubuntu:latest"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
        }
    }

    features {
        perfmon {
        }
    }
}))

