package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'CopyServiceImages'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("CopyServiceImages")
    name = "Copy service images"

    vcs {
        root(RelativeId("SshGitStashInDevexpertsCom7999enDxfeedGraalNativeApiGitRefsHeadsMainTags"))
    }

    features {
        perfmon {
        }
    }
}))

