package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'TestForLinux'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("TestForLinux")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true

    features {
        val feature1 = find<PullRequests> {
            pullRequests {
                vcsRootExtId = "${DslContext.settingsRoot.id}"
                provider = bitbucketServer {
                    serverUrl = "https://stash.in.devexperts.com"
                    authType = password {
                        username = "dxcity"
                        password = "%dxcity.token.bitbucket%"
                    }
                    filterTargetBranch = "+:refs/heads/main"
                    usePullRequestBranches = true
                }
            }
        }
        feature1.apply {
            provider = bitbucketServer {
                serverUrl = "https://stash.in.devexperts.com"
                authType = password {
                    username = "dxcity"
                    password = "credentialsJSON:103397d4-1bf1-4c41-a0aa-bb40ea0a2591"
                }
                filterSourceBranch = ""
                filterTargetBranch = "+:refs/heads/main"
                usePullRequestBranches = true
            }
        }
        val feature2 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                vcsRootExtId = "${DslContext.settingsRoot.id}"
                publisher = bitbucketServer {
                    url = "https://stash.in.devexperts.com"
                    authType = password {
                        userName = "dxcity"
                        password = "%dxcity.token.bitbucket%"
                    }
                }
            }
        }
        feature2.apply {
            publisher = bitbucketServer {
                buildName = ""
                url = "https://stash.in.devexperts.com"
                authType = password {
                    userName = "dxcity"
                    password = "credentialsJSON:103397d4-1bf1-4c41-a0aa-bb40ea0a2591"
                }
            }
        }
    }
}
