package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.DockerRegistryConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    check(archived == false) {
        "Unexpected archived: '$archived'"
    }
    archived = true

    features {
        val feature1 = find<DockerRegistryConnection> {
            dockerRegistry {
                id = "NEXUS"
                name = "Nexus"
                url = "https://nexus-docker-graalvm.in.devexperts.com"
                userName = "%dxcity.namecode.nexus%"
                password = "%dxcity.passcode.nexus%"
            }
        }
        feature1.apply {
            password = "credentialsJSON:3279f030-7991-4fcf-807b-9f8ee633d5a8"
        }
    }
}
