package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.DockerRegistryConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<DockerRegistryConnection> {
            dockerRegistry {
                id = "NEXUS"
                name = "Nexus"
                url = "https://nexus-docker-graalvm.in.devexperts.com"
                userName = "%dxcity.login%"
                password = "%dxcity.password%"
            }
        }
        feature1.apply {
            userName = "dcsi-wrp"
            password = "credentialsJSON:470f094f-33b8-48f4-b84d-25a373136566"
        }
    }
}
