# SPDX-License-Identifier: MPL-2.0

#
# Project options
#

set(DEFAULT_PROJECT_OPTIONS "")
if (DEFINED GENERIC_PROJECT_OPTIONS)
    set(DEFAULT_PROJECT_OPTIONS ${DEFAULT_PROJECT_OPTIONS} ${GENERIC_PROJECT_OPTIONS})
endif ()
set(DEFAULT_PROJECT_OPTIONS ${DEFAULT_PROJECT_OPTIONS}
        POSITION_INDEPENDENT_CODE ON
        LINKER_LANGUAGE "CXX"
        )


#
# Include directories
#

set(DEFAULT_INCLUDE_DIRECTORIES "")
if (DEFINED GENERIC_INCLUDE_DIRECTORIES)
    set(DEFAULT_INCLUDE_DIRECTORIES ${DEFAULT_INCLUDE_DIRECTORIES} ${GENERIC_INCLUDE_DIRECTORIES})
endif ()


#
# Libraries
#

set(DEFAULT_LIBRARIES "")
if (DEFINED GENERIC_LIBRARIES)
    set(DEFAULT_LIBRARIES ${DEFAULT_LIBRARIES} ${GENERIC_LIBRARIES})
endif ()


#
# Compile definitions
#

set(DEFAULT_COMPILE_DEFINITIONS "")
if (DEFINED GENERIC_COMPILE_DEFINITIONS)
    set(DEFAULT_COMPILE_DEFINITIONS ${DEFAULT_COMPILE_DEFINITIONS} ${GENERIC_COMPILE_DEFINITIONS})
endif ()


#
# Compile options
#

set(DEFAULT_COMPILE_OPTIONS "")
if (DEFINED GENERIC_COMPILE_OPTIONS)
    set(DEFAULT_COMPILE_OPTIONS ${DEFAULT_COMPILE_OPTIONS} ${GENERIC_COMPILE_OPTIONS})
endif ()


#
# Linker script
#
set(DEFAULT_LINKER_SCRIPT "")
if (DEFINED GENERIC_LINKER_SCRIPT)
    set(DEFAULT_LINKER_SCRIPT ${DEFAULT_LINKER_SCRIPT} ${GENERIC_LINKER_SCRIPT})
endif ()


#
# Linker options
#

set(DEFAULT_LINKER_OPTIONS "")
if (DEFINED GENERIC_LINKER_OPTIONS)
    set(DEFAULT_LINKER_OPTIONS ${DEFAULT_LINKER_OPTIONS} ${GENERIC_LINKER_OPTIONS} ${DEFAULT_LINKER_SCRIPT})
endif ()

# Use pthreads on mingw and linux
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU" OR "${CMAKE_SYSTEM_NAME}" MATCHES "Linux")
    set(DEFAULT_LINKER_OPTIONS
            PUBLIC
            ${DEFAULT_LINKER_OPTIONS}
            -pthread
            )
endif ()
